name: integration-test

on:
  pull_request:
    branches: [main]

jobs:

  build:
    name: Integration Tests
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v3
  
        - name: Setup JDK 17
          uses: actions/setup-java@v3
          with:
            java-version: '17'
            distribution: 'temurin'
        
        - name: Setup MySQL
          run: sudo systemctl start mysql.service

        - name: Adding logging file
          run: |
            sudo mkdir --parents /var/log/csye6225
            sudo touch /var/log/csye6225/errors.log
            sudo touch /var/log/csye6225/info.log

        - name: Giving write permissions
          run: |
            sudo chmod ugo+wx /var/log/csye6225/errors.log
            sudo chmod ugo+wx /var/log/csye6225/info.log
  
        - name: Run Spring Boot application with MySQL
          run: |
            mvn spring-boot:run -Dspring.datasource.url=jdbc:mysql://localhost:3306/cloudproject -Dspring.datasource.username=${{secrets.DB_USER_NAME}} -Dspring.datasource.password=${{secrets.DB_PASSWORD}} -Dspring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver -Dspring.jpa.hibernate.ddl-auto=update -Dspring.datasource.hikari.connection-timeout=20000 &
            sleep 40 # Wait for the service to start up
            mvn test
  
  