name: package-build

on:
  pull_request:
    branches: [main]

jobs:

  build:
    name: Integration Tests
    runs-on: ubuntu-latest

    steps:
      - name: Initial echo
        run : echo Initial Workflow file setup