name: package-build

on:
  pull_request:
    branches: [main]
  workflow_dispatch: 

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Run check
      run: echo Initial run

