name: packer-validate

on:
  pull_request:
    branches:
      - main

jobs:
  packer:
    runs-on: ubuntu-latest
    name: packer-format-validate
    steps:
      - uses: actions/checkout@v3

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main

      - name: Run `packer init`
        id: init
        run: "packer init ./build-ami.pkr.hcl"

      - name: Run `packer format`
        run: "packer fmt -check ./build-ami.pkr.hcl"

      - name: Run `packer validate`
        id: validate
        run: "packer validate ./build-ami.pkr.hcl"