name: packer-validate

on:
  pull_request:
    branches:
      - main

jobs:
  packer:
    runs-on: ubuntu-latest
    name: packer-format-validate
    
    steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - name: Checkout code
          uses: actions/checkout@v3
      
        - name: Build project
          run: mvn clean package -DskipTests

        - name: Setup `packer`
          uses: hashicorp/setup-packer@main

        - name: Run `packer init`
          id: init
          run: "packer init ./build-mi.pkr.hcl"

        - name: Run `packer format`
          run: "packer fmt -check ./build-mi.pkr.hcl"

        - name: Run `packer validate`
          id: validate
          run: "packer validate ./build-mi.pkr.hcl"