name: packer-build

on: 
    pull_request:
        branches: main
    workflow_dispatch:

jobs:
    build:
        name: Packer Build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Hello
              run: echo Hello world
